- name: Deploy to Heroku
  env:
    HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  run: |
    git config --global user.email "actions@github.com"
    git config --global user.name "GitHub Actions"
    git remote remove heroku || true
    git remote add heroku https://heroku:${HEROKU_API_KEY}@git.heroku.com/coordinatorapp.git
    git push heroku HEAD:main -f